### ISSUE TITLE
Add delay to let game launch cdaudioplr.exe

### ISSUE THREAD

**Issue by Hexaae** [YELLO-belly/cdaudio-winmm#1]
Add a feature to solve a problem with cdaudio-winmm:
cdaudioplr.exe sometimes takes too long to launch indirectly (as the game will load and use the new dll).
Can you add a sort of user-defined delay (1-2 secs) when the dll gets loaded to let it run cdaudioplr.exe in time, before the game goes on searching for the inserted audio CD?
Sometimes Pitfall starts too fast while cdaudioplr.exe is still getting launched...

**Comment by YELLO-belly** [comment]
Just to verify does it work reliably if you manually start cdaudioplr.exe before running the game?

Also have you tried using the batch file from here:
https://raw.githubusercontent.com/YELLO-belly/cdaudio-winmm/master/batch/start_game.cmd
If you put it into the game folder and edit the game.exe to match the executable name of the game and adjust the timeout number it should automate the process. Does it not work?

By default there is a 1 second delay built-in to the wrapper to handle these situations. However it is possible that the player starts extra slowly sometimes. I could never really understand what causes these issues. The idea of adding an extra user option in winmm.ini to manually input a larger or smaller delay should be possible.

**Comment by Hexaae** [comment]
Yes, exactly. Of course it works manually running first cdaudioplr.exe.

**Comment by YELLO-belly** [comment]
I am not 100% sure if adding a longer delay in the wrapper will help. The reason being that I suspect that there could be some kind of dead-lock depending on how the game is programmed and uses the threads, timing, etc... In theory the delay in winmm.dll should give time for cdaudioplr.exe to initialize. But in practice it can result in weirdness and a failure as the game may not like the forced pause. So the use of a batch file to automate the process of starting cdaudioplr.exe before running the game process might be a better solution.

However if the batch file does not work or you really do not like using it attached is a test build of winmm.dll with a hard coded 5 second delay. That may be overkill but it should serve as a good test case. If it works reliably I can program a manual startup delay configuration in winmm.ini.

[cdaudio-winmm-test-build.zip](https://github.com/YELLO-belly/cdaudio-winmm/files/10908680/cdaudio-winmm-test-build.zip)

**Comment by YELLO-belly** [comment]
Hmmm... Looking at the code it seems that there might be an issue where that start up delay is ignored if the game uses only the mciSendString method. Just in case that test build does not work and does not seem to have a 5 sec delay let me know and I will tweak the code a bit to handle this possibility.

**Comment by Hexaae** [comment]
> Hmmm... Looking at the code it seems that there might be an issue where that start up delay is ignored if the game uses only the mciSendString method. Just in case that test build does not work and does not seem to have a 5 sec delay let me know and I will tweak the code a bit to handle this possibility.

Better waiting for this fix then ;)... but yeah, I can confirm above beta works fine now with Pitfall 👍🏻 Maybe 5 secs are even too much, 3 should be safe enough.

**Comment by YELLO-belly** [comment]
Version 1.5.1 uploaded. This should solve the startup timing issues with manual control override in winmm.ini.
